name: Java Docker CI/CD

on:
  push:
    branches:
      - "test"

jobs:
  test:
    name: Run Maven Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build with Maven and run tests
        run: mvn clean test

  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Get version tag
        id: version
        run: |
          VERSION_TAG="v$(date +'%Y%m%d%H%M%S')"
          echo "VERSION_TAG=$VERSION_TAG" >> $GITHUB_ENV

      - name: Build Docker image
        run: |
          docker build . --file Dockerfile --tag lissethpacheco/delete-user-service:${VERSION_TAG} --tag lissethpacheco/delete-user-service:latest

      - name: Push Docker image
        run: |
          docker push lissethpacheco/delete-user-service:${VERSION_TAG}
          docker push lissethpacheco/delete-user-service:latest

  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
      - name: Deploy to EC2 server
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22
          script: |
            # Instala Docker si no está
            if ! command -v docker &> /dev/null; then
              sudo apt-get update
              sudo apt-get install -y docker.io
              sudo systemctl start docker
              sudo systemctl enable docker
            fi

            sudo docker pull lissethpacheco/delete-user-service:latest

            sudo docker rm -f delete-user-service 2>/dev/null || true

            sudo docker run -d --name delete-user-service -p 8085:8085 lissethpacheco/delete-user-service:latest
